### ISSUE TITLE
Preview URL PR comment should include the url

### ISSUE THREAD

**Issue by blnkt** [lsst-epo/skyviewer-client#72]
Create a PR against dev, and let it build and deploy.  It generates a comment, but the comment is missing the link to preview the PR build.

![Screen Shot 2021-11-03 at 2 53 58 PM](https://user-images.githubusercontent.com/8166060/140232327-63b71311-d0df-4cf4-bc9d-3bc4dad1e6de.png)

**Comment by jtrouth** [comment]
The version URL should now appear correctly in the comment.
